name: "Recommit"
description: "Commit and push any repository changes"
inputs:
  commit_message:
    description: "Commit message to use when committing changes"
    required: false
    default: "Apply automatic changes"
  user_name:
    description: "User name for git commits"
    required: false
    default: "github-actions[bot]"
  user_email:
    description: "User email for git commits"
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
runs:
  using: "composite"
  steps:
    - name: Configure git user
      shell: bash
      run: |
        git config user.name "${{ inputs.user_name }}"
        git config user.email "${{ inputs.user_email }}"
    - name: Commit changes if present
      shell: bash
      run: |
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "No changes to commit."
          exit 0
        fi
        git add -A
        git commit -m "${{ inputs.commit_message }}"
        git push
