name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  recommit:
    name: Auto-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Apply formatters
        uses: ./.github/actions/recommit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head_ref: ${{ github.head_ref || github.ref_name }}
          head_repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          commit_message: "chore: apply Ruff formatting"
          commands: |
            python -m pip install --upgrade pip
            pip install ruff
            ruff format .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage

      - name: Run tests with coverage
        run: |
          python -m coverage run -m pytest tests

      - name: Generate coverage report
        run: |
          python -m coverage report -m
          python -m coverage xml

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
